### ISSUE TITLE
API alignment checklist

### ISSUE THREAD

**Issue by Pessimistress** [uber-common/viewport-mercator-project#36]
- [x] Remove `FlatMercatorViewport` (legacy class) and make `PerspectiveMercatorViewport` the default export
- [x] Rename `MercatorViewport` (base class) to `Viewport`
- [ ] Rename `getLocationAtPoint` to `getMapCenterByPosition` (suggestions?)
- [x] `project` method should return depth value if `z` component is supplied (currently forced to 0)
- [ ] `metersToLngLatDelta` `lngLatDeltaToMeters` and `addMetersToLngLat`: these are not accurate conversion, but using deck.gl's approximation methods. Is any app using these? Is it more useful to offer `lngLatToMeterOffset` and `meterOffsetToLngLat`? Or just deprecate?

@ibgreen

**Comment by ibgreen** [comment]
> Rename MercatorViewport (base class) to Viewport

Sounds good. We should articulate the purpose of this base class so that the design is clear, I am getting a bit uncertain.

> Project method should return depth value if z component is supplied

Yes, at the very least this is a good default, maybe allow this to be controlled with a flag?

> metersToLngLatDelta lngLatDeltaToMeters and addMetersToLngLat
> using deck.gl's approximation methods

The way I think about these is that we would like to make it easy to unproject in deck.gl in all coordinate systems. If deck.gl apps are using layers in coordinate system meters, it stands to reason that they would like to be able to project and unproject in that system.

While I agree that it can seem somewhat arbitrary to include this approximated system in a general module, the alternative is to ask the deck.gl users to take different approaches depending on coordinate system (assuming we align the viewport systems).

Let's at least try to make a design that accommodates the meters coordinate and identity modes and see if it becomes too intrusive here.

**Comment by Pessimistress** [comment]
> The way I think about these is that we would like to make it easy to unproject in deck.gl in all coordinate systems. 
Absolutely. Yet, the `PerspectiveMercatorViewport` defined in this module is not used by deck.gl. deck.gl defines its own `WebMercatorViewport` based on a much more complex `Viewport` base class.
This module is shared between react-map-gl and deck.gl, and offers projection utilities that match the behavior of Mapbox. Anything specific to  deck.gl should be living in the deck.gl code base.

**Comment by ibgreen** [comment]
> The PerspectiveMercatorViewport defined in this module is not used by deck.gl. deck.gl defines its own WebMercatorViewport based on a much more complex Viewport base class.

>  Anything specific to deck.gl should be living in the deck.gl code base.

That is certainly one option. 

We can probably agree that it is undesirable to have two copies of very similar code being included in essentially all applications (since apps almost always use both deck.gl and react-map-gl). 

I personally, think alignment deck.gl/viewport-mercator-project is possible, but it does take considerable effort, and it could be more effort than it is worth.

**Comment by ibgreen** [comment]
The alternative IMHO is that we cut down this module to an absolute minimum of "maximally shareable" pieces.

One approach to do that is the [functional interface](https://github.com/uber-common/viewport-mercator-project/blob/master/src/web-mercator-utils.js) that I recently introduced in viewport-mercator-project. This interface is now used  by deck.gl to build a different set of viewport classes while importing most of the mercator related code from this module. 

To complete this transition, the Viewport class here would be rewritten into a thin wrapper over those functions. Almost all code would be shared, but deck.gl could build something more capable.

Also, even if we dodge the "meters question" here, we still need to solve the problem in deck.gl. I believe that we all want to offer deck.gl users a comprehensive, well designed set of projection functions that are easy to understand and cover the various aspects of the rest of the deck.gl API
